<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Stencil for Swift</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.stencil</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.swift</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.swift.stencil</string>
	<key>uuid</key>
	<string>D7B8842A-1C47-4D7E-9D2E-D65E8CD8E4FC</string>
</dict>
</plist>
